<div class="bottom_block">
    <div class="container_12">
      <div class="grid_10 prefix_1">
        <div class="column"><a href="#">Nossa Equipe</a></div>
        <div class="column"><a href="#">FAQs</a></div>
        <div class="column"><a href="#">Contato</a></div>
        <div class="clear"></div>
          <div class="socials">
            <a href="https://www.facebook.com/LuanaGalian?ref=hl" target="_new"><i class=" icon-facebook"></i></a>
            <a href="#"><i  class="icon-twitter"></i></a>
            <a href="https://plus.google.com/110988663546063958415/posts" target="_new"><i class=" icon-google-plus "></i></a>
            <a href="#"><i class=" icon-pinterest"></i></a>
          </div>
        
      </div>
    </div>
</div>
<!--==============================footer=================================-->

<footer>    
  <div class="container_12">
    <div class="grid_12">

      <div class="copy">
      Luana Galian  (C) 2014 | <a href="#">Privacy Policy</a> | Desenvolvido por <a href="http://www.gustavodelnegro.com.br/" rel="follow">Gustavo Del Negro</a>
      </div>
    </div>
  </div>
</footer>