<!DOCTYPE html>
<html lang="pt-Br">
     <head>
     <title>Luana Galian - Nutricionista</title>
     <meta charset="utf-8">
     <meta title="Luana Galian - Nutricionista">
     <meta content="Dicas de alimentação, receitas e notícias relacionadas à obtenção/manutenção de uma boa saúde com base em uma alimentação correta e saudável">
     <meta name="keywords" content="receitas saudáveis, nutrição, nutricionista, alimentação, reeducação alimentar">
     <meta name="author" content="Luana Galian">
     <link rel="icon" href="/images/favicon.ico">
     <link rel="shortcut icon" href="/images/logo.png" />
     <link rel="stylesheet" href="/css/style.css">
     <link rel="stylesheet" href="/css/font-awesome.css">
     <link rel="stylesheet" href="/css/slider.css">
     <link rel="stylesheet" href="/css/elastislide.css">
     <script src="/js/jquery.js"></script>
     <script src="/js/jquery-migrate-1.1.1.js"></script>
     <script src="/js/superfish.js"></script>
     <script src="/js/jquery.equalheights.js"></script>
     <script src="/js/jquery.easing.1.3.js"></script>
     <script src="/js/modernizr.custom.63321.js"></script>
     <script src="/js/jquerypp.custom.js"></script>
     <script src="/js/jquery.ui.totop.js"></script>
     <script src="/js/jquery.carouFredSel-6.1.0-packed.js"></script>
     <script src="/js/jquery.elastislide.js"></script>

     <script src="/js/jquery.catslider.js"></script> 
     <script src="/js/jquery.touchSwipe.min.js"></script> 
     <script>
        $(window).load (  function(){


            $( '#mi-slider' ).catslider();

            $( '#carousel' ).elastislide( {
            orientation : 'vertical'
          } );



          });

           $(window).load (
        function(){$('#carousel1').carouFredSel({auto: false, prev: '.prev1',next: '.next1', width: 220, items: {
          visible : {min: 1,
           max: 1
    },
    height: 'auto',
     width: 220,

        }, responsive: true, 

        scroll: 1, 

        mousewheel: false,

        swipe: {onMouse: false, onTouch: false}});

        } );  

        $(document).ready(function(){
          $().UItoTop({ easingType: 'easeOutQuart' });
        });  
    </script>
     <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">

    <![endif]-->
     </head>
    <body  class="page1">
<!--==============================header=================================-->
 <?php echo $this->render('header.phtml') ?>

<!--==============================Content=================================-->

        <div class="content">
            <div class="container_12">
                <?php echo $this->layout()->content; ?>	
            </div>
        </div>
        <?php echo $this->render('footer.phtml') ?>
    </body>
</html>