<div class="grid_8 prefix_2">
      <div id="mi-slider" class="mi-slider">
          <ul>
            <li class=""><a href="#"><img src="images/fruit1.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/fruit2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/fruit3.jpg" alt=""></a></li>
          </ul>
          <ul>
            <li class=""><a href="#"><img src="images/veg1.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/veg2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/veg3.jpg" alt=""></a></li>
          </ul>
          <ul>
            <li class=""><a href="#"><img src="images/meat1.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/meat2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/meat3.jpg" alt=""></a></li>
          </ul>
          <ul>
            <li class=""><a href="#"><img src="images/dier1.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/dier2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/dier3.jpg" alt=""></a></li>
          </ul>
        
          <nav>
            <a href="#">Frutas</a>
            <a href="#">Vegetais</a>
            <a href="#">Carnes</a>
            <a href="#">Laticinios</a>
          </nav>
        </div>
    </div>
    <div class="clear"></div>
    <div class="grid_8">
      <h3>Seja bem vindo</h3>
      <img src="images/rosto.jpg" alt="" class="img_inner fleft">
      <div class="extra_wrapper">
        <p>Formada em Nutrição pela Faculdade de Apucarana e atualmente cursando MBA em tecnologia e qualidade de Alimentos na Universidade Estadual de Maringá. Nutricionista clínica com atendimento nutricional personalizado, oferecendo tratamento nutricional para doenças como hipertensão, diabetes, doença cardiovascular, entre outros, além de acompanhamento e orientação nutricional e reeducação alimentar. Também consultoria e assessoria.</p>
      </div>
      <div class="clear"></div>
      <div class="grid_4 alpha">
<!--        <div class="banner maxheight"></div>-->
        <h3>Nossa missão:</h3>
        <p>Auxiliar na melhoria ou obtenção de uma maior qualidade de vida com base em uma alimentação de qualidade, a partir de:</p>
        <ul class="list">
          <li><a href="#">Reeducação alimentar.</a></li>
          <li><a href="#">Alimentação equilibrada. </a></li>          
        </ul>
      </div>
      <div class="grid_4 omega">
<!--        <div class="banner b1 maxheight"></div>-->
        <h3>O que oferecemos:</h3>
        <p>Dentre os serviços prestados, podem ser citados:</p>
        <ul class="list">
          <li><a href="#">Consultoria para acompanhamento de cardápio de empresas </a></li>
          <li><a href="#">Consultas particulares ou conveniadas </a></li>
          <li><a href="#">Acompanhamento da alimentação de funcionários.</a></li>
          <li><a href="#">Dietas para melhoria de sintomas de doenças crônicas como: diabetes, hipertensão, entre outros.</a></li>
          <li><a href="#">Consultoria para escolas, visando aumento na qualidade de vida dos alunos, promovendo um cardápio saudável. </a></li>
        </ul>
      </div>
      <div class="clear"></div>
    </div>
    <div class="grid_3 prefix_1">
      <!-- Elastislide Carousel -->
     
          <ul id="carousel" class="elastislide-list">
            <li><a href="#"><img src="images/page1_img2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img3.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img4.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img3.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img4.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img2.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img3.jpg" alt=""></a></li>
            <li><a href="#"><img src="images/page1_img4.jpg" alt=""></a></li>
          </ul>
          <!-- End Elastislide Carousel -->
           <div class="car_div">
            <div class="title">Depoimentos de pacientes</div>
          <ul id="carousel1" class="">
            <li>“Lorem ipsum dolor sit amet, tetur adipiscing elit. In ollis erat matti neque facilisis, sit amet .”</li>
            <li>"Retrolom ipsum dolor sit met, consectetur ipiscing elit. In mollis erat mattis neque."</li>
            <li>"Aliquam nibh ante, egestas id dictum a, commodo luctus libero. Praesent faucibus."</li>
        </ul>
        <a href="#" class="prev1"></a><a href="#" class="next1"></a>
        </div>