<link rel="stylesheet" href="/css/form.css">
<div class="grid_5">
      <h3>Localização</h3>
            <div class="map">
            <figure class="img_inner fleft">
                          <iframe src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Brooklyn,+New+York,+NY,+United+States&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=61.282355,146.513672&amp;ie=UTF8&amp;hq=&amp;hnear=Brooklyn,+Kings,+New+York&amp;ll=40.649974,-73.950005&amp;spn=0.01628,0.025663&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
            </figure>
          </div>
</div>
<div class="grid_6 prefix_1">
      <h3>Formulário de contato</h3>
      <form id="form">
      <div class="success_wrapper">
      <div class="success">Formulário enviado com sucesso<br>
      <strong>Entraremos em contato em breve.</strong> </div></div>
      <fieldset>
      <label class="name">
      <input type="text" value="Nome:">
      <br class="clear">
      <span class="error error-empty">*Nome inválido.</span><span class="empty error-empty">*Campo obrigatório.</span> </label>
     
      <label class="phone">
      <input type="tel" value="Tefone:">
      <br class="clear">
      <span class="error error-empty">*Número de telefone inválido.</span><span class="empty error-empty">*Campo obrigatório.</span> </label>
       <label class="email">
      <input type="text" value="E-Mail:">
      <br class="clear">
      <span class="error error-empty">*Endereço de e-mail inválido.</span><span class="empty error-empty">*Campo obrigatório.</span> </label>
      <label class="message">
      <textarea>Mensagem:</textarea>
      <br class="clear">
      <span class="error">*A mensagem é muito curta.</span> <span class="empty">*Campo obrigatório.</span> </label>
      <div class="clear"></div>
      <div class="btns"><a data-type="reset" class="">Limpar</a><a data-type="submit" class="">Enviar</a>
      <div class="clear"></div>
      </div></fieldset></form>
      <div class="st1">
      Para agendar consultas: <br>
      E-mail: <span class="col1"><a href="#">consultas@luanagalian.com.br</a></span><br>
      Telefone: (43) 9922-0494
      </div>
    </div>