    <div id="page-bottom" class="clearfix">
    	<div class="wrapper clearfix">
            <div class="clear"></div>
        </div><!--bottom-sidebar-->
        <footer id="footer" class="clearfix">
        	<div id="footer-inner">
            	<div class="wrapper">
            		<p id="copyrights">Copyright &copy; 2014 OPI System Ltda. Todos os Direitos Reservados a Editora Ribeiro de Campos</p>
                    <ul class="social-links clearfix">
                        <li class="facebook-icon">
                            <a target="_blank" title="Facebook" class="facebook" href="#"><img src="images/icons/facebook-icon.png" alt="" /></a>
                        </li>
                        <li class="twitter-icon">
                            <a target="_blank" title="Twitter" class="twitter" href="#"><img src="images/icons/twitter-icon.png" alt="" /></a>
                        </li>
                        <li class="gplus-icon">
                            <a target="_blank" title="Google plus" class="gplus" href="#"><img src="images/icons/gplus-icon.png" alt="" /></a>
                        </li>
                    </ul><!--social-links-->
                    <div class="clear"></div>
                </div>
            </div><!--footer-inner-->
        </footer>
    </div><!--page-bottom-->