<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<header id="header">
    	<div id="header-inner">
            <div class="wrapper clearfix"> 
				<div id="logo-image">
					<a href="index.html"><img src="<?php echo $baseUrl?>./placeholders/logo.png" alt="" /></a>
				</div><!--logo-image-->
                <nav id="main-nav">
                    <ul id="main-menu" class="clearfix">
                        <li class="current-menu-item"><a href="/admin/">Home</a></li>
                        <li><a href="#">Usuários</a></li>
                        <li><a href="#">Patrocinadores</a></li>
                        <li><a href="#">Slider</a></li>
                        <li><a href="#">Revista</a></li>
                        <li><a href="#">Programa</a></li>
                        <li><a href="#">Guia CasaSUL</a></li>
                        <li><a href="#">Notícias</a></li>
                    </ul><!--end:main-menu-->
                </nav><!--end:main-nav-->
            </div><!--wrapper-->
        </div><!--header-inner-->
    </header><!--header-->