<?php
function custom_echo($x)
{
  if(strlen($x)<=200)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,200) . '...';
    echo $y;
  }
}
$modeloImagem = new Admin_Model_Imagem();
?>
<div class="grid_12">
      <h3>Blog</h3>      </div>
      <div class="grid_7">
          <?php
            foreach($this->materias as $key => $materia):
          ?>
                <div class="blog">
                    <?php
                    if(!is_null($materia['thumb'])){
                        $dadosImagem = $modeloImagem->pesquisaImagem($materia['thumb']);
                    }
                    ?>
                    <img src="<?php echo $dadosImagem['local'].$dadosImagem['nome'];?>" alt="<?php echo $materia['titulo']?>" class="img_inner fleft">
                    <div class="extra_wrapper">
                      <h4><a href="<?php echo $this->url(array("controller"=>"blog","action"=>"show","id"=>$materia['idMateria']),null,true)?>"><?php echo $materia['titulo']?> </a></h4>
                      <time datetime="<?php echo $materia['dtInclusao']?>"><?php echo $materia['dtInclusao']?></time><?php echo $materia['descricao']?>
                      <br>
                      <a href="<?php echo $this->url(array("controller"=>"blog","action"=>"show","id"=>$materia['idMateria']),null,true)?>" class="link1">Veja Mais</a>
                    </div>
                </div>
          <?php
            endforeach;
          ?>
    </div>
    <div class="grid_4 prefix_1">
<!--      <h4>Categories</h4>
      <ul class="list">
        <li><a href="#">Duis massa elit, auctor non pellentesque vel.</a></li>
        <li><a href="#">Nullam eget dignissim nisi, aliquam feugiat nibh. </a></li>
        <li><a href="#">Ut nisi nibh, sagittis ut semper elementum.</a></li>
        <li><a href="#">Pellentesque a odiohasellus vitae libero vel.</a></li>
        <li><a href="#">Justo pretium dignissieger semper in estgue.</a></li>
        <li><a href="#"> In laoreet lacus eros, vel pulvinar urna ultut.</a></li>
      </ul>-->
      <h4 class="head1">Postagens recentes</h4>
      <?php 
        foreach($this->materiasRecentes as $indice => $materia):
                $dadosImagem = $modeloImagem->pesquisaImagem($materia['thumb']);
            ?>
            <div class="post">
                <div class="l_blox">
                  <img src="<?php echo $dadosImagem['local'].$dadosImagem['nome'];?>" alt="<?php echo $materia['titulo']?>">
                  <time datetime="<?php echo $materia['dtInclusao']?>"><?php echo $materia['dtInclusao']?></time>
                </div>
                <div class="extra_wrapper"><a href="<?php echo $this->url(array("controller"=>"blog","action"=>"show","id"=>$materia['idMateria']),null,true)?>"><?php echo $materia['descricao']?></a></div>
           </div>
           <?php
        endforeach;
      ?>
      <!-- <h4 class="head1">Recent Comments</h4>
      <div class="comm">
        <div class="user">
          <img src="images/page3_img7.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <p><a href="#">Admin</a></p>
            <time datetime="2013-01-01">September 14, 2013</time>
          </div>
        </div>
        Maecenas vehicula egestas venenatis.  Fertolo milotti.
Duis massa elit, auctor non pellentesque vel.
      </div> !-->
    </div>
  </div>
</div>
