<?php 
$dbImagens = new Admin_Model_DbTable_Imagens();
$imagem = $dbImagens->pesquisarImagens($this->materias['thumb']);

//$dbUsuario = new Admin_Model_DbTable_Usuario();
//$usuario = $dbUsuario->pesquisarUsuario($this->noticia['autor']);

?>

<div class="grid_12">
      <h3><?php echo $this->materias['titulo']?></h3>      </div>
      <div class="grid_7">
                <div class="blog">
                    <div class="extra_wrapper">
                        <time datetime="<?php echo nl2br($this->materias['dtInclusao'])?>"><?php echo $this->materias['dtInclusao']?></time><?php echo $this->materias['descricao']?>
                        <br> 
                        <p><img src="<?php echo $imagem['local'].$imagem['nome'];?>" alt="<?php echo $this->materias['titulo']?>" class="img_inner fleft"></p>
                        <br>
                        <p> <?php echo $this->materias['texto']?>
                   </div>
                </div>
    </div>
    <div class="grid_4 prefix_1">
<!--      <h4>Categories</h4>
      <ul class="list">
        <li><a href="#">Duis massa elit, auctor non pellentesque vel.</a></li>
        <li><a href="#">Nullam eget dignissim nisi, aliquam feugiat nibh. </a></li>
        <li><a href="#">Ut nisi nibh, sagittis ut semper elementum.</a></li>
        <li><a href="#">Pellentesque a odiohasellus vitae libero vel.</a></li>
        <li><a href="#">Justo pretium dignissieger semper in estgue.</a></li>
        <li><a href="#"> In laoreet lacus eros, vel pulvinar urna ultut.</a></li>
      </ul>-->
      <h4 class="head1">Recent Posts</h4>
      <div class="post">
        <div class="l_blox">
          <img src="images/page3_img5.jpg" alt="">
          <time datetime="2013-01-01">2013-07-04</time>
        </div>
        <div class="extra_wrapper"><a href="#">Cras facilisis, nulla vel viverra auctor, leo ame magna dales felis, quis malesuada nibher odio ut velit. Proin pharetra li luctus dia a scelerisque mi
convallis accumsan. </a></div>
      </div>
      <div class="post">
        <div class="l_blox">
          <img src="images/page3_img6.jpg" alt="">
          <time datetime="2013-01-01">2013-08-07</time>
        </div>
        <div class="extra_wrapper"><a href="#">Joas facilisis, nulla vel viverra auctor, leo ame magna dales felis, quis malesuada nibher odio ut velit. Proin pharetra li luctus dia a scelerisque mi
convallis accumer. </a></div>
      </div>
      <h4 class="head1">Recent Comments</h4>
      <div class="comm">
        <div class="user">
          <img src="images/page3_img7.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <p><a href="#">Admin</a></p>
            <time datetime="2013-01-01">September 14, 2013</time>
          </div>
        </div>
        Maecenas vehicula egestas venenatis.  Fertolo milotti.
Duis massa elit, auctor non pellentesque vel.
      </div>
      <div class="comm">
        <div class="user">
          <img src="images/page3_img7.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <p><a href="#">Admin</a></p>
            <time datetime="2013-01-01">September 14, 2013</time>
          </div>
        </div>
        Neraecenas vehicula egestas venenatis. Fertolo milottiis massa elit, auctor non pellentesq.
      </div>
    </div>
  </div>
</div>